server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    port: 6379
    host: 110.42.224.240
    database: 0
    password: 1410357039
    timeout: 1800000
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

jzj:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: 4dyWei0NXl2UdSPadFXrWanlNyImQKFz